services:
  next:
    image: ghcr.io/alexispe/cesi-next-cicd:latest
    restart: always
    ports:
      - 3000:3000
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval=30